import Vue from 'vue'
import Vuex from 'vuex'
import tool from '@/util/tool'
Vue.use(Vuex);
export default new Vuex.Store({
  state:{
    userInfo:'',
    goodsCategory:tool.getLocal('goodsCategory')||[],//商品分类列表
    lessonCategory:tool.getLocal('lessonCategory')||[],//课程分类列表
    videoCategory:tool.getLocal('videoCategory')||[],//视频课程分类列表
    articleCategory:tool.getLocal('articleCategory')||[],//资讯分类列表
    esotericaCategory:tool.getLocal('esotericaCategory')||[],//秘籍分类列表
  },
  mutations:{
    setUser(state,value){
      state.userInfo=value;
    },
    //设置商品分类列表
    setGoodsCategory(state,value){
      state.goodsCategory=value;
      tool.setLocal('goodsCategory',value);
    },
    //设置课程分类列表
    setLessonCategory(state,value){
      state.lessonCategory=value;
      tool.setLocal('lessonCategory',value);
    },
    //设置视频课程分类列表
    setVideoCategory(state,value){
      state.videoCategory=value;
      tool.setLocal('videoCategory',value);
    },
    //设置资讯分类列表
    setArticleCategory(state,value){
      state.articleCategory=value;
      tool.setLocal('articleCategory',value);
    },
    //设置秘籍分类列表
    setEsotericaCategory(state,value){
      state.esotericaCategory=value;
      tool.setLocal('esotericaCategory',value);
    },
  },
  actions:{
    //获取商品分类列表
    getGoodsCategory(context){
      tool.$http('/admin/commodity/getCategoryList',{
        page:1,
        size:1000,
      }).then(r=>{
        if(r.code==0){
          context.commit('setGoodsCategory',r.data.list);
        }
      })
    },
    //获取课程分类列表
    getLessonCategory(context){
      tool.$http('/admin/course/getCourseCategory',{
        page:1,
        size:1000,
      }).then(r=>{
        if(r.code==0){
          context.commit('setLessonCategory',r.data.list);
        }
      })
    },
    //获取视频课程分类列表
    getVideoCategory(context){
      tool.$http('/admin/video/category',{
        page:1,
        size:1000,
      }).then(r=>{
        if(r.code==0){
          context.commit('setVideoCategory',r.data.list);
        }
      })
    },
    //获取资讯分类列表
    getArticleCategory(context){
      tool.$http('/admin/article/category',{
        page:1,
        size:1000,
      }).then(r=>{
        if(r.code==0){
          context.commit('setArticleCategory',r.data.list);
        }
      })
    },
    //获取秘籍分类列表
    getEsotericaCategory(context){
      tool.$http('/admin/cheats/category',{
        page:1,
        size:1000,
      }).then(r=>{
        if(r.code==0){
          context.commit('setEsotericaCategory',r.data.list);
        }
      })
    }
  }
})
